const map = [
    "WWWWWWWWWFWWWWWWWWWWWW",
    "WWWWWWWWW WW  W  WWWWW",
    "WWWWWWW    WWW WWW WWW",
    "WWWWWWW WWW        WWW",
    "WWWWWW   WW WWWWWWWWWW",
    "WWWWWW W WW   WWW WWWW",
    "W WW   W  W W   W    W",
    "W   WW WW     W   WW W",
    "W W WWW  WW WWWWW WWWW",
    "F W  WWW   S   WW  W F",
    "WW  W W WWW WW   WWW W",
    "WW WW     W  WWW   W W",
    "WW WWW WW   WWWWWW W W",
    "WW WWW WWW WW  W WW  W",
    "WW W   WWW    WW    WW",
    "W   WWWW   WW    WW WW",
    "W W WW WWWWWW  WWW  WW",
    "W W       W   W    WWW",
    "WWWWW WWW   WW  WW WWW",
    "WWWWWWWW  WW   W   WWW",
    "WWWWWWWWWWWF WWWWWWWWW"
];
